// Copyright 2015 The go-ethereum Authors
// This file is part of the go-ethereum library.
//
// The go-ethereum library is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// The go-ethereum library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with the go-ethereum library. If not, see <http://www.gnu.org/licenses/>.

package params

import (
	"errors"
	"math"
	"math/big"
	"time"

	"github.com/dominant-strategies/go-quai/common"
)

// max returns the maximum of two uint64 values
func max(a, b uint64) uint64 {
	if a > b {
		return a
	}
	return b
}

const (
	GasLimitBoundDivisor    uint64 = 1024     // The bound divisor of the gas limit, used in update calculations.
	PercentGasUsedThreshold uint64 = 90       // Percent Gas used threshold at which the gas limit adjusts
	GenesisGasLimit         uint64 = 12000000 // Gas limit of the Genesis block.

	StateCeil                 uint64 = 50000000 // Maximum the StateCeil may ever be
	StateLimitBoundDivisor    uint64 = 1024     // The bound divisor of the gas limit, used in update calculations.
	PercentStateUsedThreshold uint64 = 90       // Percent Gas used threshold at which the gas limit adjusts

	EtxStateUsed uint64 = 10000 // state used by a simple etx

	MaximumExtraDataSize  uint64 = 32    // Maximum size extra data may be after Genesis.
	CallValueTransferGas  uint64 = 9000  // Paid for CALL when the value transfer is non-zero.
	TxGas                 uint64 = 21000 // Per transaction not creating a contract. NOTE: Not payable on data of calls between transactions.
	TxGasContractCreation uint64 = 53000 // Per transaction that creates a contract. NOTE: Not payable on data of calls between transactions.
	TxDataZeroGas         uint64 = 4     // Per byte of data attached to a transaction that equals zero. NOTE: Not payable on data of calls between transactions.
	QuadCoeffDiv          uint64 = 512   // Divisor for the quadratic particle of the memory cost equation.
	LogDataGas            uint64 = 8     // Per byte in a LOG* operation's data.
	CallStipend           uint64 = 2300  // Free gas given at beginning of call.
	ETXGas                uint64 = 21000 // Per ETX generated by opETX or normal cross-chain transfer.
	//  The etx fractions  should be based on the current  expansion number
	ETXRegionMaxFraction uint64 = 1          // The maximum fraction of transactions for cross-region ETXs
	ETXPrimeMaxFraction  uint64 = 1          // The maximum fraction of transactions for cross-prime ETXs
	ETXRLimitMin         uint64 = 50 * TxGas // Minimum possible cross-region ETX limit
	ETXPLimitMin         uint64 = 50 * TxGas // Minimum possible cross-prime ETX limit

	Sha3Gas     uint64 = 30 // Once per SHA3 operation.
	Sha3WordGas uint64 = 6  // Once per word of the SHA3 operation's data.

	JumpdestGas   uint64 = 1     // Once per JUMPDEST operation.
	EpochDuration uint64 = 30000 // Duration between proof-of-work epochs.

	CreateDataGas         uint64 = 200   //
	CallCreateDepth       uint64 = 1024  // Maximum depth of call/create stack.
	ExpGas                uint64 = 10    // Once per EXP instruction
	LogGas                uint64 = 375   // Per LOG* operation.
	CopyGas               uint64 = 3     //
	StackLimit            uint64 = 1024  // Maximum size of VM stack allowed.
	TierStepGas           uint64 = 0     // Once per operation, for a selection of them.
	LogTopicGas           uint64 = 375   // Multiplied by the * of the LOG*, per LOG transaction. e.g. LOG0 incurs 0 * c_txLogTopicGas, LOG4 incurs 4 * c_txLogTopicGas.
	CreateGas             uint64 = 32000 // Once per CREATE operation & contract-creation transaction.
	Create2Gas            uint64 = 32000 // Once per CREATE2 operation
	SelfdestructRefundGas uint64 = 24000 // Refunded following a selfdestruct operation.
	MemoryGas             uint64 = 3     // Times the address of the (highest referenced byte in memory + 1). NOTE: referencing happens on read, write and in instructions such as RETURN and CALL.

	TxDataNonZeroGas          uint64 = 16   // Per byte of data attached to a transaction that is not equal to zero. NOTE: Not payable on data of calls between transactions.
	TxAccessListAddressGas    uint64 = 2400 // Per address specified in access list
	TxAccessListStorageKeyGas uint64 = 1900 // Per storage key specified in access list

	// These have been changed during the course of the chain
	SloadGas        uint64 = 800  // This is only used in the Qi tx processing
	SelfdestructGas uint64 = 5000 // Cost of SELFDESTRUCT

	// EXP has a dynamic portion depending on the size of the exponent
	ExpByte uint64 = 50 // was raised to 50

	// Extcodecopy has a dynamic AND a static cost. This represents only the
	// static portion of the gas.
	ExtcodeCopyBase uint64 = 700

	// CreateBySelfdestructGas is used when the refunded account is one that does
	// not exist. This logic is similar to call.
	CreateBySelfdestructGas uint64 = 25000

	BaseFeeChangeDenominator = 8          // Bounds the amount the base fee can change between blocks.
	ElasticityMultiplier     = 2          // Bounds the maximum gas limit a block may have.
	InitialBaseFee           = 1 * Wei    // Initial base fee for blocks.
	MaxBaseFee               = 100 * GWei // Maximum base fee for blocks.
	InitialStateLimit        = 5000000    // Initial state fee for blocks.

	MaxCodeSize           = 24576   // Maximum bytecode to permit for a contract (24KB)
	NewMaxCodeSize        = 32768   // Maximum bytecode to permit for a contract after fork (32KB)
	MaxCodeSizeForkHeight = 2683260 // Block height at which the new 32KB code size limit activates

	// Precompiled contract gas prices

	EcrecoverGas        uint64 = 3000 // Elliptic curve sender recovery gas price
	Sha256BaseGas       uint64 = 60   // Base price for a SHA256 operation
	Sha256PerWordGas    uint64 = 12   // Per-word price for a SHA256 operation
	Ripemd160BaseGas    uint64 = 600  // Base price for a RIPEMD160 operation
	Ripemd160PerWordGas uint64 = 120  // Per-word price for a RIPEMD160 operation
	IdentityBaseGas     uint64 = 15   // Base price for a data copy operation
	IdentityPerWordGas  uint64 = 3    // Per-work price for a data copy operation

	Bn256AddGas             uint64 = 150   // Gas needed for an elliptic curve addition
	Bn256ScalarMulGas       uint64 = 6000  // Gas needed for an elliptic curve scalar multiplication
	Bn256PairingBaseGas     uint64 = 45000 // Base price for an elliptic curve pairing check
	Bn256PairingPerPointGas uint64 = 34000 // Per-point price for an elliptic curve pairing check

	// The Refund Quotient is the cap on how much of the used gas can be refunded
	RefundQuotient                  uint64 = 5
	PreviousMaxAddressGrindAttempts int    = 1000  // Previous maximum number of attempts to grind an address to a valid one
	MaxAddressGrindAttempts         int    = 10000 // Maximum number of attempts to grind an address to a valid one
	MinimumEtxGasDivisor                   = 5     // The divisor for the minimum gas for inbound ETXs (Block gas limit / MinimumEtxGasDivisor)
	MaximumEtxGasMultiplier                = 2     // Multiplied with the minimum ETX gas for inbound ETXs (Block gas limit / MinimumEtxGasDivisor) * MaximumEtxGasMultiplier
	MinEtxCount                            = 50    // These counts are used in the case where tx is not eligible to be started
	MaxEtxCount                            = 100

	// Dynamic Expansion parameters

	//  This is the threshold (range 0-100) above which the
	// score will begin the tree expansion decision process. This threshold should be
	// 	chosen high enough to not be easily triggered by minor changes in node
	// 	operating behavior, but not so high that the security efficiency becomes
	// 	unacceptably low.
	TREE_EXPANSION_THRESHOLD uint16 = math.MaxUint16

	// This is the smoothing factor (range 0-10) used by each zone in its low-pass
	// filter to gather a long running average of the zone's security efficiency
	// score. Choosing a larger will make the filter less responsive; the tree
	// expansion algorithm will be less susceptible to short term variations in the
	// efficiency score, but will take longer to decide to trigger an expansion when
	// one becomes necessary.
	TREE_EXPANSION_FILTER_ALPHA uint16 = 9

	//  Once all chains have confirmed above TREE_EXPANSION_THRESHOLD, this is
	//  the number of consecutive prime blocks that must remain above the
	//  threshold to confirm the decision to expand the tree.
	TREE_EXPANSION_TRIGGER_WINDOW uint16 = 144

	// Once the network has confirmed the decision to expand the tree, this is
	// the number of prime blocks to wait until the expansion is activated. This
	// should be chosen to give node operators some time to adjust their
	// infrastructure, if needed, to account for the upcoming network change.
	TREE_EXPANSION_WAIT_COUNT = 1024

	ConversionConfirmationContext = common.PRIME_CTX // A conversion requires a single coincident Dom confirmation
	QiToQuaiConversionGas         = 100000           // The gas used to convert Qi to Quai
	DefaultCoinbaseLockup         = 0                // The default lockup byte for coinbase rewards
	MaxCoinbaseTrancheElements    = 100              // Maximum number of elements in a coinbase tranche
)

var (
	MaxGossipsubPacketSize            = 3 << 20
	GasCeil                    uint64 = 50000000
	ColosseumGasCeil           uint64 = 50000000
	GardenGasCeil              uint64 = 50000000
	OrchardGasCeil             uint64 = 50000000
	LighthouseGasCeil          uint64 = 50000000
	LocalGasCeil               uint64 = 50000000
	DurationLimit                     = big.NewInt(5) // The decision boundary on the blocktime duration used to determine whether difficulty should go up or not.
	GardenDurationLimit               = big.NewInt(5) // The decision boundary on the blocktime duration used to determine whether difficulty should go up or not.
	OrchardDurationLimit              = big.NewInt(5) // The decision boundary on the blocktime duration used to determine whether difficulty should go up or not.
	LighthouseDurationLimit           = big.NewInt(5) // The decision boundary on the blocktime duration used to determine whether difficulty should go up or not.
	LocalDurationLimit                = big.NewInt(1) // The decision boundary on the blocktime duration used to determine whether difficulty should go up or not.
	TimeToStartTx              uint64 = 100
	BlocksPerDay               uint64 = new(big.Int).Div(big.NewInt(86400), DurationLimit).Uint64() // BlocksPerDay is the number of blocks per day assuming 5 second block time
	BlocksPerWeek              uint64 = 7 * BlocksPerDay
	BlocksPerMonth             uint64 = 30 * BlocksPerDay
	PrimeBlocksPerMonth        uint64 = BlocksPerMonth / 4                                          // TODO: has to scale properly when the network expands
	BlocksPerYear              uint64 = 365 * BlocksPerDay                                          // BlocksPerYear is the number of blocks per year assuming 5 secs blocks
	DifficultyAdjustmentPeriod        = big.NewInt(720)                                             // This is the number of blocks over which the average has to be taken
	DifficultyAdjustmentFactor int64  = 40                                                          // This is the factor that divides the log of the change in the difficulty
	MinQuaiConversionAmount           = new(big.Int).Mul(big.NewInt(10000000000), big.NewInt(GWei)) // 0.000000001 Quai
	MaxWorkShareCount                 = 16
	WorkSharesThresholdDiff           = 3 // Number of bits lower than the target that the default consensus engine uses
	ExpectedWorksharesPerBlock        = 8 // The expected number of work shares per block
	WorkShareP2PThresholdDiff         = 7 // Default value in bits lower than the target
	WorkSharesInclusionDepth          = 3 // Number of blocks upto which the work shares can be referenced and this is protocol enforced
	MaxLockupByte                     = 3 // Max lockup byte allowed in the transactions for coinbase
	LockupByteToBlockDepth            = [4]uint64{
		ConversionLockPeriod, // 2 weeks
		3 * BlocksPerMonth,   // 3 months
		6 * BlocksPerMonth,   // 6 months
		BlocksPerYear,        // 12 months
	}
	// The first value represents the multiplier that represents interest rate
	// for the first year, the second value represents the terminal rate these
	// values are divided by 100,000 to get the final values
	LockupByteToRewardsMultiple = [4][2]uint64{
		[2]uint64{},
		[2]uint64{103500, 100218},
		[2]uint64{110000, 100625},
		[2]uint64{125000, 101562},
	}
	ExchangeRate                                = big.NewInt(221077819000000000) // This is the initial exchange rate in Qi per Quai in Its/Qit.
	MaxTimeDiffBetweenBlocks             int64  = 100                            // Max time difference between the blocks to 100 secs
	OneOverAlpha                                = big.NewInt(1000)               // The alpha value for the quai to qi conversion
	ControllerKickInBlock                uint64 = 186190                         // This is in order of prime blocks
	CoinbaseLockupPrecompileKickInHeight uint64 = 112000                         // The height at which the coinbase lockup precompile is enabled
	MinBaseFeeInQits                            = big.NewInt(5)
	OneOverBaseFeeControllerAlpha               = big.NewInt(100)
	BaseFeeMultiplier                           = big.NewInt(50)

	ConversionLockPeriod uint64 = 100
	CoinbaseEpochBlocks  uint64 = 100

	// Controller related constants
	StartingKQuaiDiscount               = big.NewInt(100)
	StartingConversionFlowAmount        = new(big.Int).Mul(big.NewInt(10000), big.NewInt(Ether)) // Starting conversion flow amount in Quai
	MinConversionFlowAmount             = new(big.Int).Mul(big.NewInt(100), big.NewInt(Ether))   // Min conversion flow amount in Quai
	MinerDifficultyWindow        uint64 = 4000
	KQuaiDiscountMultiplier      int64  = 100000
	MinCubicDiscountBasisPoint   uint64 = 20
	MinCubicDiscountDivisor      uint64 = 10000
	TokenDiffAlpha                      = big.NewInt(5)

	SlipAmountRange = big.NewInt(10000)
	MaxSlip         = big.NewInt(9000)
	MinSlip         = big.NewInt(30)

	// QiActivationBlock is the approximated Zone block number for the corresponding prime controller kick in block
	QiActivationBlock uint64 = 882000
	MaxQiTxDataLength        = 22 // Qi Tx Data can only be max of 22 bytes for the WrapQi it is 20 byte and 22 (2 byte slip + 20 byte address) byte for Conversion

	ConversionSlipChangeBlock uint64 = 202800
	KQuaiChangeBlock          uint64 = 564270 // Prime block number at which k quai change happens
	KQuaiChangeHoldInterval   uint64 = 100    // Around 6-7 days worth of the prime blocks

	// KQuaiChangeTable is the table that defines the KQuai change at different blocks
	// The first value is the block number and the second value is the KQuai value left after the reduction
	KQuaiChangeTable = [][2]uint64{
		{KQuaiChangeBlock, 50},
		{KQuaiChangeBlock + 200, 75},
		{KQuaiChangeBlock + 400, 75},
		{KQuaiChangeBlock + 600, 75},
	}

	NewOpcodesForkBlock = big.NewInt(1310000) // The block at which the new opcodes are activated

	MaxAllowableEntropyDist uint64 = 40 // Maximum multiple of zone intrinsic S distance allowed from the current Entropy
)

var (
	KawPowForkBlock            uint64 = 909000           // Block at which KawPow activates
	KawPowTransitionPeriod     uint64 = BlocksPerDay / 4 // Progpow grace period after kawpow upgrade, 1 day for testnet
	TotalPowEngines            uint64 = 2                // Total number of PoW engines supported (Progpow, Kawpow)
	AuxTemplateLivenessTime    uint64 = 15
	AuxTemplateStaleTime       uint64 = uint64(10 * time.Minute)
	ShareLivenessTime          uint32 = 18             // The time in seconds that a share is considered live for the purposes of inclusion in the block reward calculation
	ShareDiffRelativeThreshold        = big.NewInt(90) // 90% of the current header diff
	AlphaInverse                      = big.NewInt(1)

	ShaBlockTime    = big.NewInt(600) // btc/bch block time 10 mins in secs
	ScryptBlockTime = big.NewInt(60)  // Doge block time 1 min in secs

	// PoW share difficulty parameters
	InitialShaDiffMultiple    = big.NewInt(167000)
	InitialScryptDiffMultiple = big.NewInt(12)

	MinPowDivisor           = big.NewInt(2) // Minimum multiple of the target difficulty that a share must meet to be valid
	PowDiffAdjustmentFactor = big.NewInt(300000)

	// Target number of shares per algo times 2^32
	TargetShaShares = big.NewInt(12884901888)
	MaxShaShares    = big.NewInt(17179869184) // 2x the target

	// Maximum number of shares that can be included in a block for each algo.
	// This is to prevent a single block from being filled with shares from one
	// specific algo
	MaxShaSharesCount    = 8
	MaxScryptSharesCount = 8

	// Maximum amount of hashrate allowed on subsidy chain
	MaxSubsidyNumerator   = big.NewInt(3)
	MaxSubsidyDenominator = big.NewInt(4)

	InitialKawpowDiff       = big.NewInt(21500000000000) // Ravencoin mainnet has 4.3Th/s
	RavenQuaiBlockTimeRatio = big.NewInt(12)             // 60s/5s = 12

	RavencoinDiffPercentage  = big.NewInt(10000) // 100% in basis points
	RavencoinDiffCutoffEnd   = big.NewInt(9000)  // 90%
	RavencoinDiffCutoffStart = big.NewInt(7500)  // 75%
	RavencoinDiffCutoffRange = big.NewInt(1500)

	// The number of blocks to use in the exponential moving average
	WorkShareEmaBlocks = big.NewInt(1000) // About 1 day worth of blocks

	// MuSig2 2-of-3 public keys for AuxTemplate signing
	// Add this to go-quai/params/protocol_params.go
	MuSig2PublicKeys = []string{
		"033073c6c8f3d296c86e79443a45ff66b64c05d9e0fda0b593adffeaa57def3381", // Key 1
		"03d6d355f016a19b1800f1c5e04f1ae1935e1a0b5803b85d349d978bbea7a2b982", // Key 2
		"03a9eb89ddab4f63503e6cef12bfc97cdb749389ad31a221fcfb672b607f8adf0c", // Key 3
	}

	// MerkleNonce, MerkleSize is used for the auxpow2
	MerkleNonce uint32 = 0
	MerkleSize  uint32 = 2

	UnlivelySharePenalty      = big.NewInt(70) // Amount of share reward left after applying the penalty for shares that are not included in the block reward calculation due to being stale
	ProgpowPenalty            = big.NewInt(70) // Amount of share reward left after applying the penalty for shares that are not included in the block reward calculation due to share being progpow after the fork
	ShareRewardPenaltyDivisor = big.NewInt(100)
)

const (
	TokenChoiceSetSize uint64 = 4000 // This should be same as the MinerDifficultyWindow
)

func CalculateLockupByteRewardsMultiple(lockupByte uint8, blockNumber uint64) (*big.Int, error) {
	if lockupByte <= 0 || lockupByte > uint8(MaxLockupByte) {
		return nil, errors.New("invalid lockup byte used")
	}
	year := blockNumber / BlocksPerYear
	if year == 0 {
		rewardsMultiple := LockupByteToRewardsMultiple[lockupByte][0]
		return big.NewInt(int64(rewardsMultiple)), nil
	} else if year > 4 {
		rewardsMultiple := LockupByteToRewardsMultiple[lockupByte][1]
		return big.NewInt(int64(rewardsMultiple)), nil
	} else {
		// using the starting and the trailing rate to establish a linear discount based on the block number
		// y = mx + c
		// let m be in the form a/b so that less precesion is lost in the final answer
		// y = (ax + cb)/b
		c := int64(LockupByteToRewardsMultiple[lockupByte][0])
		a := (int64(LockupByteToRewardsMultiple[lockupByte][1]) - int64(LockupByteToRewardsMultiple[lockupByte][0]))
		b := int64(4 * BlocksPerYear)
		x := int64(blockNumber) - int64(BlocksPerYear) // subtracting a year because the discount starts after the first year
		rewardsMultiple := (a*x + b*c) / b
		return big.NewInt(rewardsMultiple), nil
	}
}

// This is TimeFactor*TimeFactor*common.NumZonesInRegion*common.NumRegionsInPrime
func PrimeEntropyTarget(expansionNum uint8) *big.Int {
	numRegions, numZones := common.GetHierarchySizeForExpansionNumber(expansionNum)
	regionTimeFactor := int64(max(numRegions, 2))
	zoneTimeFactor := int64(max(numZones, 2))
	timeFactorMultiplied := new(big.Int).Mul(big.NewInt(regionTimeFactor), big.NewInt(zoneTimeFactor))
	return new(big.Int).Mul(timeFactorMultiplied, new(big.Int).SetUint64(numZones*numRegions))
}

// This is TimeFactor*common.NumZonesInRegion
func RegionEntropyTarget(expansionNum uint8) *big.Int {
	_, numZones := common.GetHierarchySizeForExpansionNumber(expansionNum)
	timeFactor := int64(max(numZones, 2))
	return new(big.Int).Mul(big.NewInt(timeFactor), new(big.Int).SetUint64(numZones))
}

func MinGasLimit(number uint64) uint64 {
	return 12000000
}

func OneOverKqi(number uint64) *big.Int {
	// This is the number of hashes need to get 1 Qit. 2.6e9 is ~$0.001
	baseOneOverKqi := big.NewInt(26000000)
	if number > QiActivationBlock {
		baseOneOverKqi = big.NewInt(26000)
	}
	// Based on the research done
	// https://epoch.ai/blog/predicting-gpu-performance, it seems that the
	// decrease in the transistor size and the improvements of flops from the
	// increase in cores will double every 2.69 years and will plateau sometime
	// after 2030. If we assume that this saturation happens after two
	// doublings, we can multiply the base value by 4
	doublingPeriodInBlocks := (365 * BlocksPerDay * 269) / 100

	if number > 2*doublingPeriodInBlocks {
		return new(big.Int).Mul(baseOneOverKqi, big.NewInt(4))
	} else {
		doublingCount := number / doublingPeriodInBlocks
		remainingBlocks := number % doublingPeriodInBlocks
		// 1/Kqi = 1/(2^doublingCount * baseOneOverKQi * (1 + remainingBlocks/doublingPeriodInBlocks))
		newOneOverKqi := new(big.Int).Mul(big.NewInt(int64(doublingPeriodInBlocks+remainingBlocks)), baseOneOverKqi)
		newOneOverKqi = new(big.Int).Mul(newOneOverKqi, new(big.Int).Exp(big.NewInt(2), big.NewInt(int64(doublingCount)), nil))
		newOneOverKqi = new(big.Int).Div(newOneOverKqi, big.NewInt(int64(doublingPeriodInBlocks)))
		return newOneOverKqi
	}
}

// Gas calculation functions

func SstoreSetGas(stateSize, contractSize *big.Int) uint64 {
	return CalculateGasWithStateScaling(stateSize, contractSize, 20000) // Once per SSTORE operation from clean zero to non-zero
}

func SstoreSentryGas(stateSize, contractSize *big.Int) uint64 {
	return CalculateGasWithStateScaling(stateSize, contractSize, 2300) // Minimum gas required to be present for an SSTORE call, not consumed
}

func ColdAccountAccessCost(stateSize, contractSize *big.Int) uint64 {
	return CalculateGasWithStateScaling(stateSize, contractSize, 2600) // COLD_ACCOUNT_ACCESS_COST
}

func WarmStorageReadCost(stateSize, contractSize *big.Int) uint64 {
	return CalculateGasWithStateScaling(stateSize, contractSize, 100) // WARM_STORAGE_READ_COST
}

func ColdSloadCost(stateSize, contractSize *big.Int) uint64 {
	return CalculateGasWithStateScaling(stateSize, contractSize, 2100) // COLD_SLOAD_COST
}

func SstoreResetGas(stateSize, contractSize *big.Int) uint64 {
	return CalculateGasWithStateScaling(stateSize, contractSize, 5000) // Once per SSTORE operation from clean non-zero to something else
}

func CallNewAccountGas(stateSize *big.Int) uint64 {
	return CalculateGasWithStateScaling(stateSize, big.NewInt(0), 25000) // Paid for CALL when the destination address didn't exist prior.
}

// SSTORE_CLEARS_SCHEDULE is defined as SSTORE_RESET_GAS + ACCESS_LIST_STORAGE_KEY_COST
// Which becomes: 5000 - 2100 + 1900 = 4800
func SstoreClearsScheduleRefund(stateSize, contractSize *big.Int) uint64 {
	return SstoreResetGas(stateSize, contractSize) - ColdSloadCost(stateSize, contractSize) + TxAccessListStorageKeyGas // Once per SSTORE operation for clearing an originally existing storage slot
}

func CalculateGasWithStateScaling(stateSize, contractSize *big.Int, baseRate uint64) uint64 {

	if stateSize == nil {
		stateSize = big.NewInt(0)
	}
	if contractSize == nil {
		contractSize = big.NewInt(0)
	}

	stateTrieLevels := big.NewInt(0)
	contractTrieLevels := big.NewInt(0)
	// First calculate the log2 * 2^64 of the state size and contract size and
	// add them together
	if stateSize.Cmp(common.Big1) > 0 {
		stateTrieLevels = common.LogBig(stateSize)
	}
	if contractSize.Cmp(common.Big1) > 0 {
		contractTrieLevels = common.LogBig(contractSize)
	}

	// Since the PMT used 32 byte hash as the key, the actual levels on a
	// uniformly filled trie is log16(size of leaves) = log2(size of leaves)/4
	stateTrieLevels = new(big.Int).Div(stateTrieLevels, big.NewInt(4))
	contractTrieLevels = new(big.Int).Div(contractTrieLevels, big.NewInt(4))

	totalTrieLevels := new(big.Int).Add(stateTrieLevels, contractTrieLevels)

	// If we assume that the baseRate is accurate for 5 levels (1M accounts)
	num := new(big.Int).Mul(totalTrieLevels, big.NewInt(int64(baseRate)))
	den := new(big.Int).Mul(big.NewInt(5), common.Big2e64)
	return new(big.Int).Div(num, den).Uint64()
}

func CalculateCoinbaseValueWithLockup(value *big.Int, lockupByte uint8, blockNumber uint64) *big.Int {
	if lockupByte == 0 || blockNumber < 2*BlocksPerMonth {
		return value
	} else {
		rewardsMultiple, _ := CalculateLockupByteRewardsMultiple(lockupByte, blockNumber)
		rewardValue := new(big.Int).Mul(value, rewardsMultiple)
		rewardValue = new(big.Int).Div(rewardValue, big.NewInt(100000))
		return rewardValue
	}
}

func CalculateQiGasWithUTXOSetSizeScalingFactor(scalingFactor float64, baseRate uint64) uint64 {
	if scalingFactor < 15 {
		return baseRate
	}
	return uint64(scalingFactor*float64(baseRate)) / 15
}

func GetMaxCodeSize(blockNumber uint64) int {
	if blockNumber >= MaxCodeSizeForkHeight {
		return NewMaxCodeSize
	}
	return MaxCodeSize
}
