# This file configures github.com/golangci/golangci-lint.

run:
  timeout: 3m
  tests: true
  # default is true. Enables skipping of directories:
  #   vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs-use-default: true
  skip-files:
    - core/genesis_alloc.go
    - tests
    - metrics/counter_test.go
    - metrics/histogram_test.go
    - metrics/sample_test.go
    - metrics/writer_test.go
    - metrics/init_test.go
    - metrics/metrics_test.go
    - metrics/opentsdb_test.go
    - metrics/graphite_test.go
    - metrics/ewma_test.go
    - metrics/timer_test.go
    - metrics/json_test.go
    - metrics/gauge_float64_test.go
    - metrics/registry_test.go
    - metrics/gauge_test.go
    - metrics/prometheus/collector_test.go
    - metrics/runtime_test.go
    - metrics/meter_test.go
    - metrics/resetting_timer_test.go
    - metrics/debug_test.go
    - cmd/go-quai/genesis_test.go
    - cmd/go-quai/accountcmd_test.go
    - cmd/go-quai/run_test.go
    - cmd/utils/flags_test.go
    - cmd/utils/customflags_test.go
    - cmd/utils/prompt_test.go
    - cmd/go-quai/les_test.go
    - consensus/misc/eip1559_test.go
    - consensus/blake3pow/blake3pow_test.go
    - consensus/blake3pow/sealer_test.go
    - consensus/blake3pow/consensus_test.go
    - crypto/blake2b/blake2b_test.go
    - crypto/blake2b/blake2b_f_test.go
    - crypto/ecies/ecies_test.go
    - crypto/signify/signify_test.go
    - crypto/signature_test.go
    - crypto/crypto_test.go
    - core/genesis_test.go
    - core/tx_list_test.go
    - core/headerchain_test.go
    - core/types/transaction_test.go
    - core/types/log_test.go
    - core/types/hashing_test.go
    - core/types/block_test.go
    - core/types/transaction_signing_test.go
    - core/types/bloom9_test.go
    - core/types/receipt_test.go
    - core/tx_pool_test.go
    - core/rawdb/table_test.go
    - core/rawdb/accessors_indexes_test.go
    - core/rawdb/chain_iterator_test.go
    - core/rawdb/database_test.go
    - core/rawdb/freezer_table_test.go
    - core/rawdb/accessors_chain_test.go
    - core/block_validator_test.go
    - core/chain_indexer_test.go
    - core/dao_test.go
    - core/blockchain_snapshot_test.go
    - core/blockchain_repair_test.go
    - core/forkid/forkid_test.go
    - core/blockchain_sethead_test.go
    - core/state/state_object_test.go
    - core/state/snapshot/generate_test.go
    - core/state/snapshot/iterator_test.go
    - core/state/snapshot/snapshot_test.go
    - core/state/snapshot/disklayer_test.go
    - core/state/snapshot/wipe_test.go
    - core/state/snapshot/difflayer_test.go
    - core/state/statedb_test.go
    - core/state/sync_test.go
    - core/state/trie_prefetcher_test.go
    - core/state/iterator_test.go
    - core/state/state_test.go
    - core/bloombits/scheduler_test.go
    - core/bloombits/matcher_test.go
    - core/bloombits/generator_test.go
    - core/vm/gas_table_test.go
    - core/vm/runtime/runtime_example_test.go
    - core/vm/runtime/runtime_test.go
    - core/vm/analysis_test.go
    - core/vm/instructions_test.go
    - core/vm/contracts_test.go
    - core/vm/logger_test.go
    - core/blockchain_test.go
    - core/rlp_test.go
    - core/state_processor_test.go
    - core/bench_test.go
    - core/chain_makers_test.go
    - quaistats/quaistats_test.go
    - tests/transaction_test.go
    - tests/init_test.go
    - tests/block_test.go
    - tests/state_test.go
    - tests/rlp_test.go
    - tests/vm_test.go
    - tests/fuzzers/abi/abifuzzer_test.go
    - tests/fuzzers/secp256k1/secp_test.go
    - tests/difficulty_test.go
    - rlp/decode_test.go
    - rlp/raw_test.go
    - rlp/iterator_test.go
    - rlp/encoder_example_test.go
    - rlp/decode_tail_test.go
    - rlp/encode_test.go
    - common/mclock/simclock_test.go
    - common/hexutil/hexutil_test.go
    - common/hexutil/json_example_test.go
    - common/hexutil/json_test.go
    - common/bitutil/compress_test.go
    - common/bitutil/bitutil_test.go
    - common/types_test.go
    - common/format_test.go
    - common/math/integer_test.go
    - common/math/big_test.go
    - common/fdlimit/fdlimit_test.go
    - common/prque/sstack_test.go
    - common/prque/lazyqueue_test.go
    - common/prque/prque_test.go
    - common/bytes_test.go
    - trie/stacktrie_test.go
    - trie/sync_test.go
    - trie/proof_test.go
    - trie/iterator_test.go
    - trie/encoding_test.go
    - trie/database_test.go
    - trie/node_test.go
    - trie/secure_trie_test.go
    - trie/trie_test.go
    - params/config_test.go
    - p2p/enr/enr_test.go
    - p2p/discover/table_test.go
    - p2p/discover/v5_udp_test.go
    - p2p/discover/v5wire/encoding_test.go
    - p2p/discover/v5wire/crypto_test.go
    - p2p/discover/table_util_test.go
    - p2p/rlpx/rlpx_test.go
    - p2p/rlpx/buffer_test.go
    - p2p/util_test.go
    - p2p/dial_test.go
    - p2p/nat/nat_test.go
    - p2p/nat/natupnp_test.go
    - p2p/enode/iter_test.go
    - p2p/enode/idscheme_test.go
    - p2p/enode/nodedb_test.go
    - p2p/enode/urlv4_test.go
    - p2p/enode/localnode_test.go
    - p2p/enode/node_test.go
    - p2p/message_test.go
    - p2p/msgrate/msgrate_test.go
    - p2p/transport_test.go
    - p2p/netutil/iptrack_test.go
    - p2p/netutil/net_test.go
    - p2p/netutil/error_test.go
    - p2p/dnsdisc/sync_test.go
    - p2p/dnsdisc/tree_test.go
    - p2p/dnsdisc/client_test.go
    - p2p/peer_test.go
    - p2p/server_test.go
    - log/format_test.go
    - eth/filters/filter_test.go
    - eth/filters/bench_test.go
    - eth/filters/filter_system_test.go
    - eth/filters/api_test.go
    - eth/gasprice/feehistory_test.go
    - eth/gasprice/gasprice_test.go
    - eth/handler_eth_test.go
    - eth/sync_test.go
    - eth/fetcher/block_fetcher_test.go
    - eth/fetcher/tx_fetcher_test.go
    - eth/downloader/downloader_test.go
    - eth/downloader/queue_test.go
    - eth/downloader/testchain_test.go
    - eth/abi/unpack_test.go
    - eth/abi/event_test.go
    - eth/abi/reflect_test.go
    - eth/abi/method_test.go
    - eth/abi/packing_test.go
    - eth/abi/abi_test.go
    - eth/abi/type_test.go
    - eth/abi/bind/bind_test.go
    - eth/abi/topics_test.go
    - eth/abi/pack_test.go
    - eth/handler_test.go
    - eth/api_test.go
    - eth/protocols/eth/protocol_test.go
    - eth/protocols/eth/handshake_test.go
    - eth/protocols/eth/handler_test.go
    - eth/protocols/eth/peer_test.go
    - node/utils_test.go
    - node/node_example_test.go
    - node/rpcstack_test.go
    - node/node_test.go
    - node/config_test.go
    - node/api_test.go
    - rpc/testservice_test.go
    - rpc/http_test.go
    - rpc/types_test.go
    - rpc/websocket_test.go
    - rpc/subscription_test.go
    - rpc/client_example_test.go
    - rpc/client_test.go
    - rpc/server_test.go
    - event/example_test.go
    - event/event_test.go
    - event/example_feed_test.go
    - event/subscription_test.go
    - event/example_scope_test.go
    - event/feed_test.go
    - event/example_subscription_test.go
    - ethdb/leveldb/leveldb_test.go
    - ethdb/memorydb/memorydb_test.go
    - quaiclient/ethclient/ethclient_test.go

linters:
  disable-all: true
  enable:
    - goconst
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
    - typecheck

linters-settings:
  gofmt:
    simplify: true
  goconst:
    min-len: 3 # minimum length of string constant
    min-occurrences: 6 # minimum number of occurrences

issues:
  exclude-rules:
    - path: crypto/blake2b/
      linters:
        - deadcode
    - path: crypto/bn256/cloudflare
      linters:
        - deadcode
    - path: p2p/discv5/
      linters:
        - deadcode
    - path: core/vm/instructions_test.go
      linters:
        - goconst
    - path: internal/build/pgp.go
      text: 'SA1019: "golang.org/x/crypto/openpgp" is deprecated: this package is unmaintained except for security fixes.'
  exclude:
    - 'SA1019: event.TypeMux is deprecated: use Feed'