// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package core

import (
	"encoding/json"
	"errors"
	"math/big"

	"github.com/dominant-strategies/go-quai/common"
	"github.com/dominant-strategies/go-quai/common/hexutil"
	"github.com/dominant-strategies/go-quai/common/math"
	"github.com/dominant-strategies/go-quai/params"
)

var _ = (*genesisSpecMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (g Genesis) MarshalJSON() ([]byte, error) {
	type Genesis struct {
		Config     *params.ChainConfig     `json:"config"`
		Nonce      math.HexOrDecimal64     `json:"nonce"`
		Timestamp  math.HexOrDecimal64     `json:"timestamp"`
		ExtraData  hexutil.Bytes           `json:"extraData"`
		GasLimit   math.HexOrDecimal64     `json:"gasLimit"   gencodec:"required"`
		Difficulty *math.HexOrDecimal256   `json:"difficulty" gencodec:"required"`
		Mixhash    common.Hash             `json:"mixHash"`
		Coinbase   common.Address          `json:"coinbase"`
		Alloc      []params.GenesisAccount `json:"alloc"      gencodec:"required"`
		Number     []math.HexOrDecimal64   `json:"number"`
		GasUsed    math.HexOrDecimal64     `json:"gasUsed"`
		ParentHash []common.Hash           `json:"parentHash"`
		BaseFee    *math.HexOrDecimal256   `json:"baseFeePerGas"`
	}
	var enc Genesis
	enc.Config = g.Config
	enc.Nonce = math.HexOrDecimal64(g.Nonce)
	enc.Timestamp = math.HexOrDecimal64(g.Timestamp)
	enc.ExtraData = g.ExtraData
	enc.Mixhash = g.Mixhash
	enc.Coinbase = g.Coinbase
	enc.Number = make([]math.HexOrDecimal64, common.HierarchyDepth)
	enc.ParentHash = make([]common.Hash, common.HierarchyDepth)
	for i := 0; i < common.HierarchyDepth-1; i++ {
		enc.Number[i] = math.HexOrDecimal64(g.Number[i])
		enc.ParentHash[i] = g.ParentHash[i]
	}
	enc.GasLimit = math.HexOrDecimal64(g.GasLimit)
	enc.GasUsed = math.HexOrDecimal64(g.GasUsed)
	enc.BaseFee = (*math.HexOrDecimal256)(g.BaseFee)
	enc.Difficulty = (*math.HexOrDecimal256)(g.Difficulty)
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (g *Genesis) UnmarshalJSON(input []byte) error {
	type Genesis struct {
		Config     *params.ChainConfig     `json:"config"`
		Nonce      *math.HexOrDecimal64    `json:"nonce"`
		Timestamp  *math.HexOrDecimal64    `json:"timestamp"`
		ExtraData  *hexutil.Bytes          `json:"extraData"`
		GasLimit   *math.HexOrDecimal64    `json:"gasLimit"   gencodec:"required"`
		Difficulty *math.HexOrDecimal256   `json:"difficulty" gencodec:"required"`
		Mixhash    *common.Hash            `json:"mixHash"`
		Coinbase   *common.Address         `json:"coinbase"`
		Alloc      []params.GenesisAccount `json:"alloc"      gencodec:"required"`
		Number     []*math.HexOrDecimal64  `json:"number"`
		GasUsed    *math.HexOrDecimal64    `json:"gasUsed"`
		ParentHash []*common.Hash          `json:"parentHash"`
		BaseFee    *math.HexOrDecimal256   `json:"baseFeePerGas"`
	}
	var dec Genesis
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Config != nil {
		g.Config = dec.Config
	}
	if dec.Nonce != nil {
		g.Nonce = uint64(*dec.Nonce)
	}
	if dec.Timestamp != nil {
		g.Timestamp = uint64(*dec.Timestamp)
	}
	if dec.ExtraData != nil {
		g.ExtraData = *dec.ExtraData
	}
	if dec.Mixhash != nil {
		g.Mixhash = *dec.Mixhash
	}
	if dec.Alloc == nil {
		return errors.New("missing required field 'alloc' for Genesis")
	}
	if dec.GasLimit == nil {
		return errors.New("missing required field 'gasLimit' for Genesis")
	}
	g.GasLimit = uint64(*dec.GasLimit)
	if dec.GasUsed != nil {
		g.GasUsed = uint64(*dec.GasUsed)
	}
	if dec.Difficulty == nil {
		return errors.New("missing required field 'difficulty' for Genesis")
	}
	g.Difficulty = (*big.Int)(dec.Difficulty)
	if dec.BaseFee != nil {
		g.BaseFee = (*big.Int)(dec.BaseFee)
	}
	if dec.Coinbase != nil {
		g.Coinbase = *dec.Coinbase
	}
	for i := 0; i < common.HierarchyDepth; i++ {
		if dec.Number[i] != nil {
			g.Number[i] = uint64(*dec.Number[i])
		}
		if dec.ParentHash[i] != nil {
			g.ParentHash[i] = *dec.ParentHash[i]
		}
	}
	return nil
}
