// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: p2p/node/peerManager/peerdb/peer_info.proto

package peerdb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoPeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddrInfo      *ProtoAddrInfo         `protobuf:"bytes,1,opt,name=addrInfo,proto3" json:"addrInfo,omitempty"`
	PubKey        []byte                 `protobuf:"bytes,2,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	Entropy       uint64                 `protobuf:"varint,3,opt,name=entropy,proto3" json:"entropy,omitempty"`
	Protected     bool                   `protobuf:"varint,4,opt,name=protected,proto3" json:"protected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoPeerInfo) Reset() {
	*x = ProtoPeerInfo{}
	mi := &file_p2p_node_peerManager_peerdb_peer_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoPeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoPeerInfo) ProtoMessage() {}

func (x *ProtoPeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_node_peerManager_peerdb_peer_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoPeerInfo.ProtoReflect.Descriptor instead.
func (*ProtoPeerInfo) Descriptor() ([]byte, []int) {
	return file_p2p_node_peerManager_peerdb_peer_info_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoPeerInfo) GetAddrInfo() *ProtoAddrInfo {
	if x != nil {
		return x.AddrInfo
	}
	return nil
}

func (x *ProtoPeerInfo) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

func (x *ProtoPeerInfo) GetEntropy() uint64 {
	if x != nil {
		return x.Entropy
	}
	return 0
}

func (x *ProtoPeerInfo) GetProtected() bool {
	if x != nil {
		return x.Protected
	}
	return false
}

type ProtoAddrInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Addrs         []string               `protobuf:"bytes,2,rep,name=Addrs,proto3" json:"Addrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoAddrInfo) Reset() {
	*x = ProtoAddrInfo{}
	mi := &file_p2p_node_peerManager_peerdb_peer_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoAddrInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoAddrInfo) ProtoMessage() {}

func (x *ProtoAddrInfo) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_node_peerManager_peerdb_peer_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoAddrInfo.ProtoReflect.Descriptor instead.
func (*ProtoAddrInfo) Descriptor() ([]byte, []int) {
	return file_p2p_node_peerManager_peerdb_peer_info_proto_rawDescGZIP(), []int{1}
}

func (x *ProtoAddrInfo) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ProtoAddrInfo) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

var File_p2p_node_peerManager_peerdb_peer_info_proto protoreflect.FileDescriptor

const file_p2p_node_peerManager_peerdb_peer_info_proto_rawDesc = "" +
	"\n" +
	"+p2p/node/peerManager/peerdb/peer_info.proto\x12\x06peerdb\"\x92\x01\n" +
	"\rProtoPeerInfo\x121\n" +
	"\baddrInfo\x18\x01 \x01(\v2\x15.peerdb.ProtoAddrInfoR\baddrInfo\x12\x16\n" +
	"\x06pubKey\x18\x02 \x01(\fR\x06pubKey\x12\x18\n" +
	"\aentropy\x18\x03 \x01(\x04R\aentropy\x12\x1c\n" +
	"\tprotected\x18\x04 \x01(\bR\tprotected\"5\n" +
	"\rProtoAddrInfo\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x14\n" +
	"\x05Addrs\x18\x02 \x03(\tR\x05AddrsB;Z9github.com/dominant-strategies/go-quai/peerManager/peerdbb\x06proto3"

var (
	file_p2p_node_peerManager_peerdb_peer_info_proto_rawDescOnce sync.Once
	file_p2p_node_peerManager_peerdb_peer_info_proto_rawDescData []byte
)

func file_p2p_node_peerManager_peerdb_peer_info_proto_rawDescGZIP() []byte {
	file_p2p_node_peerManager_peerdb_peer_info_proto_rawDescOnce.Do(func() {
		file_p2p_node_peerManager_peerdb_peer_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_p2p_node_peerManager_peerdb_peer_info_proto_rawDesc), len(file_p2p_node_peerManager_peerdb_peer_info_proto_rawDesc)))
	})
	return file_p2p_node_peerManager_peerdb_peer_info_proto_rawDescData
}

var file_p2p_node_peerManager_peerdb_peer_info_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_p2p_node_peerManager_peerdb_peer_info_proto_goTypes = []any{
	(*ProtoPeerInfo)(nil), // 0: peerdb.ProtoPeerInfo
	(*ProtoAddrInfo)(nil), // 1: peerdb.ProtoAddrInfo
}
var file_p2p_node_peerManager_peerdb_peer_info_proto_depIdxs = []int32{
	1, // 0: peerdb.ProtoPeerInfo.addrInfo:type_name -> peerdb.ProtoAddrInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_p2p_node_peerManager_peerdb_peer_info_proto_init() }
func file_p2p_node_peerManager_peerdb_peer_info_proto_init() {
	if File_p2p_node_peerManager_peerdb_peer_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_p2p_node_peerManager_peerdb_peer_info_proto_rawDesc), len(file_p2p_node_peerManager_peerdb_peer_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_p2p_node_peerManager_peerdb_peer_info_proto_goTypes,
		DependencyIndexes: file_p2p_node_peerManager_peerdb_peer_info_proto_depIdxs,
		MessageInfos:      file_p2p_node_peerManager_peerdb_peer_info_proto_msgTypes,
	}.Build()
	File_p2p_node_peerManager_peerdb_peer_info_proto = out.File
	file_p2p_node_peerManager_peerdb_peer_info_proto_goTypes = nil
	file_p2p_node_peerManager_peerdb_peer_info_proto_depIdxs = nil
}
