{{- $name := include "go-quai.name" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    networking.gke.io/managed-certificates: {{ $name }}
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: {{ $name }}
  name: {{ $name }}
  namespace: {{ .Values.goQuai.env }}
spec:
  defaultBackend:
    service:
      name: prime-{{- $name }}
      port:
        name: http
  rules:
{{- range $chain := .Values.goQuai.chains }}
{{ include "go-quai.ingress" $ | replace "prime" $chain.name | indent 4 }}
{{- end }}
