// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: common/proto_common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoLocation) Reset() {
	*x = ProtoLocation{}
	mi := &file_common_proto_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoLocation) ProtoMessage() {}

func (x *ProtoLocation) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoLocation.ProtoReflect.Descriptor instead.
func (*ProtoLocation) Descriptor() ([]byte, []int) {
	return file_common_proto_common_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoLocation) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ProtoHash struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoHash) Reset() {
	*x = ProtoHash{}
	mi := &file_common_proto_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoHash) ProtoMessage() {}

func (x *ProtoHash) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoHash.ProtoReflect.Descriptor instead.
func (*ProtoHash) Descriptor() ([]byte, []int) {
	return file_common_proto_common_proto_rawDescGZIP(), []int{1}
}

func (x *ProtoHash) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ProtoHashes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hashes        []*ProtoHash           `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoHashes) Reset() {
	*x = ProtoHashes{}
	mi := &file_common_proto_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoHashes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoHashes) ProtoMessage() {}

func (x *ProtoHashes) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoHashes.ProtoReflect.Descriptor instead.
func (*ProtoHashes) Descriptor() ([]byte, []int) {
	return file_common_proto_common_proto_rawDescGZIP(), []int{2}
}

func (x *ProtoHashes) GetHashes() []*ProtoHash {
	if x != nil {
		return x.Hashes
	}
	return nil
}

type ProtoAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoAddress) Reset() {
	*x = ProtoAddress{}
	mi := &file_common_proto_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoAddress) ProtoMessage() {}

func (x *ProtoAddress) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoAddress.ProtoReflect.Descriptor instead.
func (*ProtoAddress) Descriptor() ([]byte, []int) {
	return file_common_proto_common_proto_rawDescGZIP(), []int{3}
}

func (x *ProtoAddress) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ProtoNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         uint64                 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoNumber) Reset() {
	*x = ProtoNumber{}
	mi := &file_common_proto_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoNumber) ProtoMessage() {}

func (x *ProtoNumber) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoNumber.ProtoReflect.Descriptor instead.
func (*ProtoNumber) Descriptor() ([]byte, []int) {
	return file_common_proto_common_proto_rawDescGZIP(), []int{4}
}

func (x *ProtoNumber) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type ProtoLocations struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locations     []*ProtoLocation       `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoLocations) Reset() {
	*x = ProtoLocations{}
	mi := &file_common_proto_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoLocations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoLocations) ProtoMessage() {}

func (x *ProtoLocations) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoLocations.ProtoReflect.Descriptor instead.
func (*ProtoLocations) Descriptor() ([]byte, []int) {
	return file_common_proto_common_proto_rawDescGZIP(), []int{5}
}

func (x *ProtoLocations) GetLocations() []*ProtoLocation {
	if x != nil {
		return x.Locations
	}
	return nil
}

var File_common_proto_common_proto protoreflect.FileDescriptor

const file_common_proto_common_proto_rawDesc = "" +
	"\n" +
	"\x19common/proto_common.proto\x12\x06common\"%\n" +
	"\rProtoLocation\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"!\n" +
	"\tProtoHash\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"8\n" +
	"\vProtoHashes\x12)\n" +
	"\x06hashes\x18\x01 \x03(\v2\x11.common.ProtoHashR\x06hashes\"$\n" +
	"\fProtoAddress\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"#\n" +
	"\vProtoNumber\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x04R\x05value\"E\n" +
	"\x0eProtoLocations\x123\n" +
	"\tlocations\x18\x01 \x03(\v2\x15.common.ProtoLocationR\tlocationsB/Z-github.com/dominant-strategies/go-quai/commonb\x06proto3"

var (
	file_common_proto_common_proto_rawDescOnce sync.Once
	file_common_proto_common_proto_rawDescData []byte
)

func file_common_proto_common_proto_rawDescGZIP() []byte {
	file_common_proto_common_proto_rawDescOnce.Do(func() {
		file_common_proto_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_common_proto_rawDesc), len(file_common_proto_common_proto_rawDesc)))
	})
	return file_common_proto_common_proto_rawDescData
}

var file_common_proto_common_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_common_proto_common_proto_goTypes = []any{
	(*ProtoLocation)(nil),  // 0: common.ProtoLocation
	(*ProtoHash)(nil),      // 1: common.ProtoHash
	(*ProtoHashes)(nil),    // 2: common.ProtoHashes
	(*ProtoAddress)(nil),   // 3: common.ProtoAddress
	(*ProtoNumber)(nil),    // 4: common.ProtoNumber
	(*ProtoLocations)(nil), // 5: common.ProtoLocations
}
var file_common_proto_common_proto_depIdxs = []int32{
	1, // 0: common.ProtoHashes.hashes:type_name -> common.ProtoHash
	0, // 1: common.ProtoLocations.locations:type_name -> common.ProtoLocation
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_proto_common_proto_init() }
func file_common_proto_common_proto_init() {
	if File_common_proto_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_common_proto_rawDesc), len(file_common_proto_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_common_proto_goTypes,
		DependencyIndexes: file_common_proto_common_proto_depIdxs,
		MessageInfos:      file_common_proto_common_proto_msgTypes,
	}.Build()
	File_common_proto_common_proto = out.File
	file_common_proto_common_proto_goTypes = nil
	file_common_proto_common_proto_depIdxs = nil
}
