// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.25.1
// source: common/proto_common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoLocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ProtoLocation) Reset() {
	*x = ProtoLocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoLocation) ProtoMessage() {}

func (x *ProtoLocation) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoLocation.ProtoReflect.Descriptor instead.
func (*ProtoLocation) Descriptor() ([]byte, []int) {
	return file_common_proto_common_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoLocation) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ProtoHash struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ProtoHash) Reset() {
	*x = ProtoHash{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoHash) ProtoMessage() {}

func (x *ProtoHash) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoHash.ProtoReflect.Descriptor instead.
func (*ProtoHash) Descriptor() ([]byte, []int) {
	return file_common_proto_common_proto_rawDescGZIP(), []int{1}
}

func (x *ProtoHash) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_common_proto_common_proto protoreflect.FileDescriptor

var file_common_proto_common_proto_rawDesc = []byte{
	0x0a, 0x19, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x22, 0x25, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x21, 0x0a, 0x09, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x48, 0x61, 0x73, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x2f, 0x5a,
	0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6f, 0x6d, 0x69,
	0x6e, 0x61, 0x6e, 0x74, 0x2d, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x69, 0x65, 0x73, 0x2f,
	0x67, 0x6f, 0x2d, 0x71, 0x75, 0x61, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_proto_common_proto_rawDescOnce sync.Once
	file_common_proto_common_proto_rawDescData = file_common_proto_common_proto_rawDesc
)

func file_common_proto_common_proto_rawDescGZIP() []byte {
	file_common_proto_common_proto_rawDescOnce.Do(func() {
		file_common_proto_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_proto_common_proto_rawDescData)
	})
	return file_common_proto_common_proto_rawDescData
}

var file_common_proto_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_proto_common_proto_goTypes = []interface{}{
	(*ProtoLocation)(nil), // 0: common.ProtoLocation
	(*ProtoHash)(nil),     // 1: common.ProtoHash
}
var file_common_proto_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_common_proto_init() }
func file_common_proto_common_proto_init() {
	if File_common_proto_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_proto_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoLocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoHash); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_proto_common_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_common_proto_goTypes,
		DependencyIndexes: file_common_proto_common_proto_depIdxs,
		MessageInfos:      file_common_proto_common_proto_msgTypes,
	}.Build()
	File_common_proto_common_proto = out.File
	file_common_proto_common_proto_rawDesc = nil
	file_common_proto_common_proto_goTypes = nil
	file_common_proto_common_proto_depIdxs = nil
}
