{
 "title": "Go-quai Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Internal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "State DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(StateTimes{label=~\".*\"}[1m])",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "TxPool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(TxpoolGauges{label=~\".*\"}[1m])",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Stream Counters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "StreamGauges{label=\"NumStreams\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Message Counters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(MessageCounters{label=\"received\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(MessageCounters{label=\"sent\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cumulative Number of Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "PeerGauges{label=\"numPeers\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Usage System vs Go-quai",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "cpu_usage{usage_type=\"Go-quai\"}",
     "legendFormat": "{{usage_type}}"
    },
    {
     "expr": "cpu_usage{usage_type=\"System\"}",
     "legendFormat": "{{usage_type}}"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "I/O Wait",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "cpu_usage{usage_type=\"Iowait\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mem_usage{usage_type=\"Stack\"}",
     "legendFormat": "{{usage_type}}"
    },
    {
     "expr": "mem_usage{usage_type=\"Used\"}",
     "legendFormat": "{{usage_type}}"
    },
    {
     "expr": "mem_usage{usage_type=\"Swap\"}",
     "legendFormat": "{{usage_type}}"
    }
   ]
  },
  {
   "title": "Disk IO/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "disk_usage{usage_type!=\"Iops\"}",
     "legendFormat": "{{usage_type}}"
    }
   ]
  },
  {
   "title": "Number of IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "disk_usage{usage_type=\"Iops\"}",
     "legendFormat": "{{usage_type}}"
    }
   ]
  },
  {
   "title": "Number of Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    { "expr": "net_usage", "legendFormat": "{{net_type}}" }
   ]
  }
 ]
}