name: Build and Deploy to Prod
on: workflow_dispatch
jobs:
  buildDeployProd:
    uses: ./.github/workflows/build-deploy.yml
    secrets:
      DOCKER: ${{ secrets.DOCKER }}
      GH_PAT: ${{ secrets.GH_PAT }}
      GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
      GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
    with:
      env: quai-prod
      awk: sed "s/-.*//g" | awk -F. '{print $1"."$2"."$3+1}'
      rails: '[[ ! "$VERSION" =~ "rc" ]] && [[ ! "$VERSION" =~ "pre" ]]'
